name: Terraform Apply

on:
  schedule:
    - cron: '00 6 * * *'  # Runs every day at 12:57 UTC
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          workspace: "${{ secrets.TF_WORKSPACE }}"
          directory: "."
        env:
          TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
          TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

      - name: Trigger Apply Run
        id: apply
        run: |
          echo "Triggering apply..."
          curl --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
               --header "Content-Type: application/vnd.api+json" \
               --request POST \
               --data '{
                 "data": {
                   "type": "runs",
                   "relationships": {
                     "workspace": {
                       "data": {
                         "type": "workspaces",
                         "id": "${{ secrets.WORKSPACE_ID }}"
                       }
                     }
                   }
                 }
               }' \
               https://app.terraform.io/api/v2/runs \
               --silent --show-error --fail --output response.json
        env:
          TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

      - name: Extract Apply Run ID
        id: extract_run_id
        run: |
          run_id=$(jq -r '.data.id' response.json)
          echo "apply_run_id=$run_id" >> $GITHUB_ENV
          echo "::set-output name=apply_run_id::$run_id"
