name: Terraform Server Management

on:
  schedule:
    # Server creation at 4:30 PM India time (11:00 AM UTC)
    - cron: '00 11 * * *'
    # Server destruction at 4:40 PM India time (11:10 AM UTC)
    - cron: '10 11 * * *'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create or Destroy Server
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          # Get current time in UTC
          current_time=$(date -u +%H:%M)
          echo "Current UTC time is $current_time"
          
          # Check if it's time to create the server
          if [[ "$current_time" == "11:00" ]]; then
            echo "Creating the server..."
            terraform apply -auto-approve
          # Check if it's time to destroy the server  
          elif [[ "$current_time" == "11:10" ]]; then
            echo "Destroying the server..."
            terraform destroy -auto-approve
          else
            echo "It's not the scheduled time for creation or destruction"
            exit 0
          fi
          
      - name: Terraform Output
        if: success()
        run: |
          terraform output -json
